sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
#install:
#  - pip install -r requirements/dev.txt
before_script:
  - make run &
script:
  - make test
  - pkill -f FLASK_APP
