sudo: false
language: python
python:
  - 3.6
install:
  - python setup.py develop
before_script:
  - gunicorn --bind 127.0.0.1:5000 --log-level debug captiveportal:app &
  - sleep 5
script:
  - python -m unittest discover -s tests
after_script:
  - pkill -f gunicorn
