sudo: false
language: python
python:
- 3.6
install:
- python setup.py develop
before_script:
- gunicorn --bind 127.0.0.1:5000 --log-level debug captiveportal:app &
- sleep 5
script:
- python -m unittest discover -s tests
after_script:
- pkill -f gunicorn
notifications:
  pushover:
    api_key:
      secure: mtvlMwCmsnAfiOaBAX1SG0y8/wRFpFxS54kZyoRqeRXI4daTfDj6uvHlpilSNvNmQsfET9KS0FjDRUnXZ6OcQVdZ6Wo4ODft+CEgZt99xOAPxtvpXDAwX1wstFjwi1vBVngAVWiJ3pXjpFOKM0TK8FcHKSm0Y8BT0PA2P2EPRe2PDlxIDawvTXV9JmvY5uSxR0nnj8e92rYV+1qG1yAxCIfh3W3YDvoHwA9FoKjCGUFxjAsYWS9VgowMxIDiuxREW3jAkmLLnPuW6MtaCriijC1B9nDofYt4gj+mlWhZ6T0H0oSHU+tZmClYEw0MoO5XUvTfJ5qQhNHH4m+snr3SNXexTxf3Og5WlaBzt/Ug15BnXVp9Z9eBGFY+pequYALqPB8hgVT+dfL7f2R1wVISjx60OwM/Cr+ZrkgmcRGo/yeOs6gu4ahw0hfBG0idG4tQ/EXgMcIMTsnUtaOQgjQDymC9p7uvae5zd5vmlEDNXK+cle5EXu11sBV6bd9y6oqMTBzS+jcqQ45KEhmmNBiD55UjgRT1qMFUpQpXULsv7+4qrVmdKOwY1X6y/p43/Q1BNYtsCa8+/xZQPtiPOL2bpl95XJhgcbFRyqy04y7XZY5M7CgZhs3452CxZl/u2fPvF4tbzXz08E96K60diQBIOjaMbH27K1lYfPUsjoXCz5U=
    users:
      secure: VU1tg069SqrhkP/rYtEIu8qJl7VE2LY/Gwf2Zo4yp8AXEp1AZwppEW9wUQbH1Hv1j08xp8lNvIRsTqKM0wry5huXB22tZYr1c2NUUH5VSkToxmSbF3dzw8odUSfyQ032vMh/nJxmQDyAR3TuOE6twZz5NAAK7/gSBC0Daq1kaKyjuB9rt1WTMFRFL0HthIFzp5Pv9FiTMPQS0+w+DYkuvetSTjvgEnjoiizo/4nadRswFoTiicnzrtUJoMtL48E+7MEc4WLe8Wak5/hYK/P9eaowuDWPd2lEIg4yglGkS511NHA0sVi2Cf+qNSTyly0I83zPxe4BP2/5v4Y8av3QVlkYLiy9AyDGdZF0hViMduy5YUfGbFPISIgGdPapaVwpQmFISAfxVc3l9zxg62q9hFJP+wmDlAc7hGAzvsXpfhtSiqfnEnQGnjH7Pqrda86BXHDLXizNl2jxhJdYuuaUgch0niIF8/RgwkUBEGGUfay9YojoMZrCRfYB2JFi3jeViykECr3reOGBQzszZPKA6tIMT5O4Xm8jUraSrGcSVoWC/SsdhXSKGxY3XTp88hG004HmFcWG/FpcHARHblJsFEC17tMdboVmSvYPXcFAltPvO9CwOw6Df0TRbAiA1pbnVjNonrgDJkT7mim9orVSQ3ZbF9hWfdIXNqRQhrLfXfw=
