sudo: false
language: python
python:
  - 3.6
install:
  - python setup.py develop
before_script:
  - gunicorn --bind 127.0.0.1:5000 --log-level debug captiveportal:app &
  - sleep 5
script:
  - python -m unittest discover -s tests
after_script:
  - pkill -f gunicorn
notifications:
  pushover:
    api_key:
      secure: N/gijfVLJT1j+zy4/YBtVlvnkw4+EbNzmmXSE0rEmrtDxBCb8j117IA2ys4tZs/bgThlGlHZqAraxSSV16Q1zDqqicRSiLZloq8r3SbT4+rwme/RMWRkcHGzB0TWJ174pNxfr/0zwZlNBQPz4XRGycNfhItvt+Kr+k+gALrBj+hPNGQWJPcpwSzi62IZeecb5GDif2/BMwDWRZe8qSpWegya1TyuMokpuVqtjP+Fhj2T59qgavHxIISlfaAgoOdqglA77ycf2K65ZbZp7zqAx2HAIF23wbieIf1ZU/dP12FksPk8f5FxtZTxOlVcVMwhwO92z7Cv3646VD4iBKE43TjwqOCQthWKOkfl8O5DKNwQVerg7J3OWb43h/zcecMPDY6rENSounRanTvy+A1vw/YL5/KEZXGzUkz59fnSunOU59ygUicUMuBRiycN3TyEVeT9hkxJB3xpBAb2VsyLFF6JcKA6LDLH8DssYazkby7ZuDjOnh3L4Cj8mVFNgRCJ8uii2W41eDTaGFGX2LKEQedaeXo8C9PlqcluSDON6s1c75SFJ9CFRP+kkmigoXsTTC5w2R8ka0cw9XBiS1TzSNsbBJuEVNW4xJRVbXUUOh1a9NUBpfEsGblpGmaNk7JXPcewuIxWOsmXWXIi1cJrZepBta7NnxvWoZC46oooZ+U=
    users:
      secure: Y43M9dytne1To7Z3waNFfWzCBSaKd1bf6iVruyNjnsmAzPlOXs/HMjdwBk/BLFi0ZQBH+yryh5RdlY4RFbZqa3ePJ+WcKeI6u+kZBMHcf1DAW60n/jeF4Lxr37Ai63wn5qY/yjOFHPdCaRtQ1z3GkU7dMZ1WmA1u2XBl5owU/xWDPIlCufXN2pY9ePEa+UEq5qpGjYLolnUbWc9PvhzAXqXvOTL+0yKLwDXhCzgQapVUgRyTlRFVZXflndgSziE+CQWuZWdjHAfIxzR4wLwRrHL5Ffobxir5b3NnPg3qN/8JMg9uZCVuw6xhqiR7wETKVuh11RVGKwtZUQM8JpAvHBB1tyjRJRPUrX7BdNZ2+PwCXXLHfZR1oAXHTZ/3tBHgqt3GGPGnpKrcZsnGA1/UKvINja4PS/03YKnxZWAEaDsF2KQBCsJvoBky61WfonCYHpqdKVhS6AegAfXGPXRAda4hK48XPHNoj0gM9s0ZrG2x7jiZolFvGl7HDqjo5V607zIey/fHDj9OtlKFkemqN7Lzq2NjlagNzokV8MQKNHbzbYVFbTn+SfEummuw1hZPyL6kXaRF7kPWBMT0P3GQm6PW+3H5BhEZdvkxYaKmwqPwsIjpX2SnUBcEYhdGnwn0S8awVhGRx3qsaL0r7YD44uOod8Em1DWJNaKEh6Bc+GA=

