sudo: false  # http://docs.travis-ci.com/user/migrating-from-legacy/
language: python
python:
  - 3.6
install:
  - python setup.py develop
before_script:
  - FLASK_APP=captiveportal flask run &
script:
  - python -m unittest discover -s tests
  - pkill -f FLASK_APP
