sudo: false
language: python
python:
  - 3.6
install:
  - python setup.py develop
before_script:
  - CAPTIVEPORTAL_SETTINGS=settings.cfg FLASK_APP=captiveportal flask run &
script:
  #- python -m unittest discover -s tests
  - curl http://127.0.0.1:5000
  - pkill -f FLASK_APP
after_script:
  - cat *.log
